# Generated by Django 3.0.5 on 2020-04-20 15:03

from django.db import migrations, models
import sh_blog.models


class Migration(migrations.Migration):

    dependencies = [
        ('sh_blog', '0003_auto_20200412_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=sh_blog.models.user_media_path),
        ),
    ]
