# Generated by Django 3.0.5 on 2020-04-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh_blog', '0004_auto_20200420_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
