# Generated by Django 3.0.5 on 2020-04-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh_blog', '0007_auto_20200428_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(default='no-avatar-300x300.jpg', max_length=200),
        ),
    ]
